---
abstract: 'Declare conflicts for your distro'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Conflicts
requires:
  Dist::CheckConflicts: '0.02'
  Dist::Zilla: '4.0'
  Dist::Zilla::File::InMemory: '0'
  Dist::Zilla::Role::FileGatherer: '0'
  Dist::Zilla::Role::InstallTool: '0'
  Dist::Zilla::Role::MetaProvider: '0'
  Dist::Zilla::Role::PrereqSource: '0'
  Dist::Zilla::Role::TextTemplate: '0'
  Moose: '0'
  Moose::Autobox: '0.09'
  namespace::autoclean: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Conflicts
  homepage: http://metacpan.org/release/Dist-Zilla-Plugin-Conflicts
  repository: git://git.urth.org/Dist-Zilla-Plugin-Conflicts.git
version: '0.13001'
x_authority: cpan:DROLSKY
x_contributors:
  - 'Karen Etheridge <ether@cpan.org>'
