---
abstract: 'Declare conflicts for your distro'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Conflicts
requires:
  Dist::CheckConflicts: 0
  Dist::Zilla: 4
  Moose::Autobox: 0.09
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-Conflicts
  repository: http://hg.urth.org/hg/Dist-Zilla-Plugin-Conflicts
version: 0.03
