---
abstract: 'Provide information on conflicts for {{ $dist_name }}'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Conflicts
requires:
  Dist::CheckConflicts: 0.02
  Dist::Zilla: 4.0
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::InstallTool: 0
  Dist::Zilla::Role::MetaProvider: 0
  Dist::Zilla::Role::PrereqSource: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Moose::Autobox: 0.09
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pg-CLI
  homepage: http://metacpan.org/release/Pg-CLI
  repository: git://git.urth.org/Pg-CLI.git
version: 0.10
x_authority: cpan:DROLSKY
